"use strict";var T=Object.create;var $=Object.defineProperty;var k=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var A=Object.getPrototypeOf,D=Object.prototype.hasOwnProperty;var _=(n,s,l,f)=>{if(s&&typeof s=="object"||typeof s=="function")for(let c of E(s))!D.call(n,c)&&c!==l&&$(n,c,{get:()=>s[c],enumerable:!(f=k(s,c))||f.enumerable});return n};var m=(n,s,l)=>(l=n!=null?T(A(n)):{},_(s||!n||!n.__esModule?$(l,"default",{value:n,enumerable:!0}):l,n));const C=require("siyuan");async function J(){const n=(await import("https://esm.sh/siyuan-noob@1.3.13/customMenu/index.js")).default,s=(await import("https://esm.sh/siyuan-noob@1.3.13/utilKernel/kernelApi.js")).default,l=await import("https://esm.sh/es-module-lexer"),f=(await import("https://esm.sh/magic-string")).default;await l.init,n.编辑器菜单.registMenuItem({id:"运行笔记",文字:"运行到代码片段(js)",图标:"#iconCode",判定函数:()=>!document.querySelector(`script[id="snippetJS${n.编辑器菜单.菜单状态.当前块id}js"]`),点击回调函数:()=>{j(!0)}}),n.编辑器菜单.registMenuItem({id:"保存笔记为js",文字:"保存文档到js但不运行",图标:"#iconCode",判定函数:()=>!document.querySelector(`script[id="snippetJS${n.编辑器菜单.菜单状态.当前块id}js"]`),点击回调函数:()=>{j()}}),n.编辑器菜单.registMenuItem({id:"重新运行笔记",文字:"重新保存代码片段(js)",图标:"#iconCode",判定函数:()=>document.querySelector(`script[id="snippetJS${n.编辑器菜单.菜单状态.当前块id}js"]`),点击回调函数:()=>{j(!0)}}),n.编辑器菜单.registMenuItem({id:"关闭笔记",文字:"关闭代码片段(js)",图标:"#iconCode",判定函数:()=>document.querySelector(`script[id="snippetJS${n.编辑器菜单.菜单状态.当前块id}js"]`),点击回调函数:()=>{c()}});async function c(){let e=n.编辑器菜单.菜单状态.当前块id+"js",o=await s.getSnippet({type:"all",enabled:2}),t=o.snippets.findIndex(i=>i.id===e);o.snippets[t].enabled=!1,await s.setSnippet(o),window.location.reload()}async function j(r){let e=n.编辑器菜单.菜单状态.当前块id,o=await s.getDoc({id:e,mode:0,size:102400,k:""},""),t=await s.getDocInfo({id:e,mode:0,size:102400,k:""},""),i=document.createElement("div");i.innerHTML=o.content;let p=i.querySelectorAll("div[data-node-id]:not(div[data-node-id] div[data-node-id])");i.querySelectorAll('[data-type="block-ref"]').forEach(d=>{d.innerText=d.getAttribute("data-id")});let a="";p.forEach(d=>{if(d.querySelector(".protyle-action__language")&&["js","javascript"].indexOf(d.querySelector(".protyle-action__language").innerHTML)>=0)a+=d.querySelector(".hljs").innerText;else if(d.querySelector(".protyle-action__language")&&["css"].indexOf(d.querySelector(".protyle-action__language").innerHTML)>=0){let w=d.querySelector(".hljs").innerText;if(w.startsWith("/*cssInJS*/")){let g=`<style>${w}</style>`;a+=`
document.head.insertAdjacentHTML('beforeend',\`${g}\`);
`}}else d.querySelectorAll('div[contenteditable="true"]').forEach(g=>{g.innerText.split(/\r\n|\n|\r/).forEach(h=>{h.startsWith("@js:import")?a+=h.replace("@js:","")+`
`:a+="//"+h+`
`})})}),a=b(a),a=`//siyuan://blocks/${t.id}
`+a,window.location.href.indexOf("?")>=0?a=`//${window.location.href.replace("app","desktop")}&&blockID=${t.id}
`+a:a=`//${window.location.href.replace("app","desktop")}?blockID=${t.id}
`+a,a=`//${t.name}
`+a;let M=new Blob([a],{type:"application/javascript"}),I="/data/snippets/jsInNote/"+t.id+".js",v=new File([M],t.id+".js",{lastModified:Date.now()}),u=new FormData;u.append("path",I),u.append("file",v),u.append("isDir",!1),u.append("modTime",Date.now());let y=await(await fetch("/api/file/putFile",{method:"POST",body:u})).json();y.code===0?(await s.pushMsg({msg:`${t.id}已经导出到${"/data/snippets/jsInNote/"+t.id+".js"}`}),r&&await x(t.id,t.name,"js")):(await s.pushErrMsg({msg:`${t.id}导出为js出错:${y.msg}`}),console.error(`${t.id}导出为js出错:${y.msg}`))}async function x(r,e,o){let t=`import('/snippets/jsInNote/${r+".js"}')`,i=await s.getSnippet({type:"all",enabled:2}),p=i.snippets.findIndex(a=>a.id===r+"js");p>=0?(i.snippets[p].content=t,i.snippets[p].name=e,i.snippets[p].type=o,i.snippets[p].enabled?(await s.setSnippet(i),window.location.reload()):(i.snippets[p].enabled=!0,await s.setSnippet(i),document.head.appendChild(S("script",{id:`snippetJS${r}`,type:"text/javascript"},t)))):(i.snippets.push({id:r+"js",content:t,name:e,type:o,enabled:!0}),await s.setSnippet(i),document.head.appendChild(S("script",{id:`snippetJS${r}`,type:"text/javascript"},t)))}function S(r,e,o){let t=document.createElement(r);return Object.getOwnPropertyNames(e).forEach(i=>t.setAttribute(i,e[i])),t.innerHTML=o,t}function b(r){let[e,o]=l.parse(r),t=new f(r);return e.forEach(i=>{t.overwrite(i.s,i.e,q(i))}),t.toString()}function q(r){let e=r.n;return e=e.replace(/\\/g,"/"),e=e.replace("//","/"),/^\d{14}\-[0-9a-z]{7}$/.test(e)?(e=`./${e}.js`,e):e.startsWith("./")||e.startsWith("../")||e.startsWith("./")||e.startsWith("/")?e:"https://esm.sh/"+e}}class O extends C.Plugin{constructor(){super()}onload(){J()}onunload(){}}module.exports=O;
